name: Update Image

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  update-image:
    name: Update Image
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - uses: actions/checkout@v3
      # install just
      - uses: extractions/setup-just@v1
      # build and push new image
      - run: |
          docker login --username acheronfail --password-stdin <<< "${{ secrets.DOCKER_TOKEN }}"
          just push
